# ============================================================================
# SCRIPT 2: Convert Integrated Peaks to ppm Values
# ============================================================================
#
# PURPOSE:
#   This script takes the integrated peak areas from Script 1 and converts
#   them to ppm (parts per million) concentration values using:
#   1. A calibration factor specific to your instrument
#   2. The volume of sample injected
#   3. The baseline CO2 concentration measured during the injection
#
# INPUT FILES:
#   integrated_injections_CO2_*.csv
#   (Generated by Script 1)
#
# OUTPUT FILES GENERATED:
#   ppm_samples_CO2_*.csv
#   - One file per integrated_injections file
#   - Contains volume-normalized ppm values for each peak
#
# KEY CONCEPT - LABEL PARSING:
#   Your sample labels must include the injection volume in a parseable format:
#   Examples:
#     - "Sample_1_0mL_" → 1.0 mL injected
#     - "Std_0_5ml_" → 0.5 mL injected
#     - "Sample-1-5mL" → 1.5 mL injected
#   The script extracts ALL numeric values from the label and assumes the
#   FIRST one is the injection volume. Format the label accordingly!
#
# CALIBRATION FACTOR:
#   This is instrument-specific. Obtain it by:
#   1. Running a known-concentration standard through the same injection method
#   2. Calculate: factor = measured_peaksum / expected_ppm / volume_injected
#   3. Or use values from your Li-COR documentation
#
# ============================================================================

# Clean Global environment
rm(list = ls())

# ============================================================================
# SECTION 1: CONFIGURE DIRECTORIES
# ============================================================================

# TO USE TEST DATA (if available):
# project_root <- paste0(dirname(rstudioapi::getSourceEditorContext()$path),
#                        "/EXAMPLE_PROJECT")

# TO USE YOUR OWN DATA (uncomment and edit):
project_root <- "C:/Users/Camille Minaudo/OneDrive - Universitat de Barcelona/Documentos/PROJECTS/2026_DRYINGLAKE/data/DIC_smallVolumes_tests/IRGA/Timeincubationtest/"

# ========================================================================
# VALIDATE AND CREATE PATHS
# ========================================================================

if (!dir.exists(project_root)) {
  stop("ERROR: project_root does not exist: ", project_root,
       "\nPlease edit the project_root variable above.")
}

folder_results <- paste0(project_root, "/Results_ppm")

if (!dir.exists(folder_results)) {
  stop("ERROR: Results folder not found: ", folder_results,
       "\nDid you run Script 1 first?")
}

message("[Script 2] Project root: ", project_root)
message("[Script 2] Results folder: ", folder_results)

# ============================================================================
# SECTION 2: LOAD REQUIRED PACKAGES
# ============================================================================

required_pkgs <- c(
  "tidyverse",      # Data manipulation and visualization
  "readxl",         # Excel file reading
  "lubridate",      # Date/time handling
  "stringr"         # String manipulation
)

for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    message("Installing package: ", pkg)
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}

message("[Script 2] All required packages loaded successfully")

# ============================================================================
# SECTION 3: CALIBRATION FACTOR
# ============================================================================
# Set the calibration factor for your instrument here
#
# IMPORTANT: This must be specific to YOUR Li-COR instrument
#
# How to determine it:
#   1. Inject a known-concentration standard (e.g., 100 ppm CO2)
#   2. Let Script 1 integrate the peak → get peaksum value
#   3. Calculate: factor = peaksum / (expected_ppm * volume_injected_ml)
#   4. This factor should be consistent across multiple standard runs
#
# If you don't have a calibration factor yet:
#   - Use factor = 1 as a placeholder (gives relative measurements)
#   - After calibrating your instrument, update this value
#
# For multiple gases (CH4, N2O, etc.), you would need separate factors
# per gas and calibration curve

factor_CO2 <- 1  # <-- UPDATE THIS WITH YOUR CALIBRATION VALUE

message("[Script 2] Using calibration factor for CO2: ", factor_CO2)
message("[Script 2] NOTE: If this is not your actual calibration factor,")
message("[Script 2]       update the 'factor_CO2' variable above and re-run this script")

# ============================================================================
# SECTION 4: IDENTIFY FILES TO PROCESS
# ============================================================================
# Find which integrated_injections files have already been converted to ppm
# (to avoid reprocessing if you re-run this script)

message("\n[Script 2] ========== Checking Files to Process ==========")

# Get all integrated peak files
integrated_files <- list.files(
  path = folder_results,
  pattern = "^integrated_injections_",
  full.names = FALSE
)

if (length(integrated_files) == 0) {
  stop("ERROR: No integrated_injections files found in ",
       folder_results, "\nDid you run Script 1 first?")
}

message("[Script 2] Found ", length(integrated_files), 
        " integrated peak file(s)")

# Get all existing ppm files (to identify which ones need processing)
ppm_files <- list.files(
  path = folder_results,
  pattern = "^ppm_samples_",
  full.names = FALSE
)

# Extract the identifiers (e.g., "CO2_rawfile_01")
integrated_ids <- gsub(".csv", "", 
                       gsub("integrated_injections_", "", integrated_files))
ppm_ids <- gsub(".csv", "", 
                gsub("^ppm_samples_", "", ppm_files))

# Find which integrated files don't have corresponding ppm files yet
integrated_to_convert <- integrated_ids[
  !(integrated_ids %in% ppm_ids)
]

if (length(integrated_to_convert) == 0) {
  message("[Script 2] All integrated files have already been converted to ppm")
  message("[Script 2] If you want to reconvert, delete the ppm_samples_* files")
  message("[Script 2] and re-run this script")
} else {
  message("[Script 2] Need to convert: ", length(integrated_to_convert), 
          " file(s)")
}

# ============================================================================
# SECTION 5: CONVERT INTEGRATED PEAKS TO PPM
# ============================================================================

message("\n[Script 2] ========== Converting Peaks to ppm ==========")

for (i in integrated_to_convert) {
  
  message("\n[Script 2] Processing: ", i)
  
  # ====================================================================
  # Extract gas name from file identifier
  # ====================================================================
  # File names are formatted as: "CO2_rawfile_01"
  # so the first 3 characters indicate the gas
  
  gasname <- tolower(substr(i, 1, 3))
  
  message("  - Gas: ", toupper(gasname))
  
  # ====================================================================
  # Get appropriate calibration factor
  # ====================================================================
  # In this version, we only handle CO2, but this could be extended
  
  if (gasname == "co2") {
    factor <- factor_CO2
  } else {
    warning("Unknown gas: ", gasname, ". Using default factor = 1")
    factor <- 1
  }
  
  message("  - Calibration factor: ", factor)
  
  # ====================================================================
  # Read integrated peaks file
  # ====================================================================
  
  input_file <- paste0(folder_results, "/integrated_injections_", i, ".csv")
  
  if (!file.exists(input_file)) {
    warning("File not found: ", input_file)
    next
  }
  
  message("  - Reading: ", basename(input_file))
  
  integrated <- tryCatch({
    read.csv(input_file, stringsAsFactors = FALSE)
  }, error = function(e) {
    warning("Error reading file: ", e$message)
    return(NULL)
  })
  
  if (is.null(integrated) || nrow(integrated) == 0) {
    warning("File is empty or unreadable: ", input_file)
    next
  }
  
  message("  - Read ", nrow(integrated), " peak records")
  
  # ====================================================================
  # STEP 1: Parse peak_id to extract sample information
  # ====================================================================
  # peak_id format: "SampleName-VolumeInML-1"
  # We need to extract:
  #   - sample: The sample identifier (everything before the last hyphen-number)
  #   - ml_injected: The injection volume in mL
  #
  # IMPORTANT: The label MUST contain the volume as the FIRST numeric value
  # Examples:
  #   "Sample-1-0mL-1" → sample="Sample-1-0mL", ml=1.0
  #   "Std-0-5ml-1" → sample="Std-0-5ml", ml=0.5
  
  message("  - Parsing peak IDs and extracting injection volumes")
  
  peak_ppm <- integrated %>%
    # Split peak_id by hyphens
    separate(peak_id, 
             into = c("sample", "ml_injected", "peak_no"),
             sep = "_",
             remove = FALSE,
             extra = "drop")  %>%  # Handle cases with extra underscores
    # Extract numeric values from ml_injected column
    mutate(
      # Use stringr to extract the first number from the string
      # This handles formats like "1", "1mL", "1.0mL", etc.
      ml_injected = as.numeric(
        gsub("[^0-9.]", "", ml_injected)
      ),
      
      # Ensure we have valid volume values
      ml_injected = if_else(
        is.na(ml_injected) | ml_injected <= 0,
        1.0,  # Default to 1 mL if parsing failed
        ml_injected
      ),
      
      # Add gas identifier (uppercase)
      gas = gasname,
      
      # Convert baseline from ppb to ppm (divide by 1000)
      peak_baseppm = peak_base / 1000,
      
      # Zero out negative baselines (instrument errors)
      # Negative baselines don't make physical sense
      peak_baseppm = if_else(
        peak_baseppm < 0,
        0,
        peak_baseppm
      ),
      
      # Calculate ppm using the calibration factor
      # ppm = (peaksum / (factor * volume)) + baseline_ppm
      ppm = (peaksum / (factor * ml_injected)) + peak_baseppm
    ) %>%
    # Select final columns for output
    select(
      dayofanalysis,
      gas,
      sample,
      ml_injected,
      peak_id,
      ppm,
      peaksum,
      peak_baseppm,
      unixtime_ofmax
    ) %>%
    # Add datetime for convenience
    mutate(
      datetime = as.POSIXct(unixtime_ofmax, 
                           tz = "CET",
                           origin = "1970-01-01")
    )
  
  # ====================================================================
  # STEP 2: Validate conversion results
  # ====================================================================
  
  # Check for any NaN or Inf values in ppm (indicates calculation errors)
  invalid_ppm <- sum(is.na(peak_ppm$ppm) | is.infinite(peak_ppm$ppm))
  
  if (invalid_ppm > 0) {
    warning("  - WARNING: ", invalid_ppm, " records with invalid ppm values")
    message("    Check that ml_injected was parsed correctly from labels")
  }
  
  # Check ppm range (typical CO2 values are 0-1000 ppm)
  min_ppm <- min(peak_ppm$ppm, na.rm = TRUE)
  max_ppm <- max(peak_ppm$ppm, na.rm = TRUE)
  
  message("  - ppm range: ", round(min_ppm, 2), " to ", round(max_ppm, 2))
  
  if (min_ppm < -100 || max_ppm > 10000) {
    warning("  - WARNING: Unusual ppm range detected")
    message("    Check calibration factor and volume parsing")
  }
  
  # ====================================================================
  # STEP 3: Save results
  # ====================================================================
  
  output_file <- paste0(folder_results, "/ppm_samples_", i, ".csv")
  
  write.csv(peak_ppm, file = output_file, row.names = FALSE)
  
  message("  - Saved: ", basename(output_file))
  message("    Records: ", nrow(peak_ppm))
  
}  # End of file loop

# ============================================================================
# SECTION 6: SUMMARY AND NEXT STEPS
# ============================================================================

message("\n[Script 2] ========== COMPLETE ==========")

# Recount files
new_ppm_files <- list.files(
  path = folder_results,
  pattern = "^ppm_samples_",
  full.names = FALSE
)

message("[Script 2] Total ppm_samples files created: ", length(new_ppm_files))
message("[Script 2] Output folder: ", folder_results)

message("\n[Script 2] Next step: Run Script 3 (3_Summary_of_samples_IRGA.R)")
message("[Script 2] to create summary statistics across all samples")

# ============================================================================
# END OF SCRIPT 2
# ============================================================================
