# ============================================================================
# SCRIPT 3: Summary Statistics of All Samples
# ============================================================================
#
# PURPOSE:
#   This script compiles ppm data from all injection replicates across
#   all samples and dates, and produces summary tables with:
#   1. Mean, SD, and count for each sample using ALL injections
#   2. Mean, SD, and count for each sample using BEST 3 injections
#   3. Full injection-level data for further analysis
#
#   The script intelligently decides whether to use all injections or
#   discard outliers based on whether the coefficient of variation (CV)
#   improves when using only the best N injections.
#
# INPUT FILES:
#   ppm_samples_CO2_*.csv
#   (Generated by Script 2)
#
# OUTPUT FILES GENERATED:
#   1. All_Summary_co2_allinjections.csv
#      - Summary using all available injections
#      - Columns: dayofanalysis, sample, avg_ppm, sd_ppm, n_used, n_discarded
#
#   2. All_Summary_co2_best3inj.csv
#      - Summary using best 3 injections (if CV improves)
#      - Columns: dayofanalysis, sample, avg_ppm, sd_ppm, n_used, n_discarded
#
#   3. All_Injections_ppm_co2.csv
#      - Individual ppm for every single injection
#      - Useful for quality control and further analysis
#
# CV-BASED FILTERING LOGIC:
#   For each sample:
#     1. Calculate CV using all N injections
#     2. Calculate CV using best 3 injections (if N >= 3)
#     3. If CV(best 3) < CV(all), report the best 3 mean/SD
#     4. Otherwise, report the all-injections mean/SD
#   This approach automatically detects and minimizes the impact of
#   outlier measurements while maintaining transparency about which
#   were discarded.
#
# ============================================================================

# Clean Global environment
rm(list = ls())

# ============================================================================
# SECTION 1: CONFIGURE DIRECTORIES
# ============================================================================

# TO USE TEST DATA (if available):
# project_root <- paste0(dirname(rstudioapi::getSourceEditorContext()$path),
#                        "/EXAMPLE_PROJECT")

# TO USE YOUR OWN DATA (uncomment and edit):
project_root <- "C:/Users/Camille Minaudo/OneDrive - Universitat de Barcelona/Documentos/PROJECTS/2026_DRYINGLAKE/data/DIC_smallVolumes_tests/IRGA/Timeincubationtest/"

# ========================================================================
# VALIDATE DIRECTORY
# ========================================================================

if (!dir.exists(project_root)) {
  stop("ERROR: project_root does not exist: ", project_root,
       "\nPlease edit the project_root variable above.")
}

folder_results <- paste0(project_root, "/Results_ppm/")

if (!dir.exists(folder_results)) {
  stop("ERROR: Results folder not found: ", folder_results,
       "\nDid you run Scripts 1 and 2 first?")
}

message("[Script 3] Project root: ", project_root)
message("[Script 3] Results folder: ", folder_results)

# ============================================================================
# SECTION 2: LOAD REQUIRED PACKAGES
# ============================================================================

required_pkgs <- c(
  "tidyverse",      # Data manipulation (dplyr, tidyr, etc.)
  "readxl"          # Excel file reading (if needed)
)

for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    message("Installing package: ", pkg)
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}

message("[Script 3] All required packages loaded successfully")

# ============================================================================
# SECTION 3: DEFINE HELPER FUNCTION - SELECT BEST N INJECTIONS
# ============================================================================
# This function finds the N injections with the lowest coefficient of
# variation (most similar to each other), which tends to give the most
# reliable mean estimate

#' Select measurements with lowest coefficient of variation
#'
#' Given a vector of measurements, returns the subset of n measurements
#' with the lowest CV among all possible combinations.
#'
#' PURPOSE:
#'   When you have replicate measurements and want to identify the most
#'   consistent subset (e.g., the 3 most similar out of 5 replicates),
#'   this function finds the combination with lowest CV.
#'
#' PARAMETERS:
#'   measurements (numeric vector): All available measurements
#'   n (integer): Number of measurements to select (default: 3)
#'
#' RETURNS:
#'   (numeric vector): The n measurements with lowest CV among all combinations
#'
#' EXAMPLE:
#'   measurements <- c(100.1, 100.2, 100.3, 95.5, 100.4)
#'   best <- select_lowest_cv(measurements, n = 3)
#'   # Returns: 100.1, 100.2, 100.3 (ignoring the outlier 95.5)

select_lowest_cv <- function(measurements, n = 3) {
  
  # Remove NA values
  measurements <- measurements[!is.na(measurements)]
  
  # Check if we have enough measurements
  if (length(measurements) < n) {
    warning(paste0(
      "Only ", length(measurements),
      " valid measurements found, returning all (needed ", n, ")"
    ))
    return(measurements)
  }
  
  # Generate all possible combinations of n measurements
  # For example, with 5 measurements and n=3, generates C(5,3)=10 combinations
  combos <- combn(measurements, n, simplify = FALSE)
  
  # Calculate CV for each combination
  # CV = (standard deviation / mean) * 100
  cvs <- sapply(combos, function(x) {
    if (mean(x) == 0) {
      # Avoid division by zero
      return(Inf)
    }
    return((sd(x) / mean(x)) * 100)
  })
  
  # Select the combination with the lowest CV
  best_combo <- combos[[which.min(cvs)]]
  
  return(best_combo)
}

message("[Script 3] Helper function 'select_lowest_cv' loaded")

# ============================================================================
# SECTION 4: IMPORT PPM DATA
# ============================================================================
# Compile all ppm measurements from all samples and dates

message("\n[Script 3] ========== Importing ppm Data ==========")

# Locate all ppm files
co2_ppm_files <- list.files(
  folder_results,
  pattern = "^ppm_samples_CO2",
  recursive = TRUE,
  full.names = TRUE
)

if (length(co2_ppm_files) == 0) {
  stop("ERROR: No ppm_samples_CO2 files found in ", folder_results,
       "\nDid you run Scripts 1 and 2 first?")
}

message("[Script 3] Found ", length(co2_ppm_files), " ppm file(s)")

# Read and combine all ppm files
co2 <- NULL

for (i in co2_ppm_files) {
  message("  - Reading: ", basename(i))
  
  file_data <- tryCatch({
    read_csv(i, show_col_types = FALSE)
  }, error = function(e) {
    warning("Error reading file: ", i, " - ", e$message)
    return(NULL)
  })
  
  if (!is.null(file_data)) {
    if (is.null(co2)) {
      co2 <- file_data
    } else {
      co2 <- rbind(co2, file_data)
    }
  }
}

if (is.null(co2) || nrow(co2) == 0) {
  stop("ERROR: No ppm data successfully read from files")
}

# Convert to data frame and ensure data types are correct
co2 <- as.data.frame(co2)

message("[Script 3] Total ppm records compiled: ", nrow(co2))
message("[Script 3] Date range: ",
        format(min(as.Date(co2$dayofanalysis), na.rm = TRUE), "%d-%b-%Y"),
        " to ",
        format(max(as.Date(co2$dayofanalysis), na.rm = TRUE), "%d-%b-%Y"))

# ============================================================================
# SECTION 5: CALCULATE STATISTICS WITH ALL INJECTIONS
# ============================================================================
# Group by sample and day, calculate mean, SD, and count

message("\n[Script 3] ========== Calculating Statistics ==========")
message("[Script 3] Method 1: Using ALL injections")

all_injections_summary <- co2 %>%
  group_by(gas, sample, dayofanalysis) %>%
  summarise(
    avg_ppm = mean(ppm, na.rm = TRUE),
    sd_ppm = sd(ppm, na.rm = TRUE),
    cv = (sd_ppm / avg_ppm) * 100,  # Coefficient of variation as percentage
    n_all = sum(!is.na(ppm)),       # Number of injections
    .groups = "drop"
  )

message("[Script 3]   - ", nrow(all_injections_summary), 
        " unique sample-day combinations")

# ============================================================================
# SECTION 6: CALCULATE STATISTICS WITH BEST 3 INJECTIONS
# ============================================================================
# For samples with 3+ injections, select the best 3 and recalculate

message("[Script 3] Method 2: Using best 3 injections (if n >= 3)")

best3_summary <- co2 %>%
  group_by(gas, sample, dayofanalysis) %>%
  # First check: only proceed if we have at least 3 injections
  mutate(
    total_injections = sum(!is.na(ppm))
  ) %>%
  filter(total_injections >= 3) %>%
  # Apply the selection function to each group
  reframe(
    ppm_selected = select_lowest_cv(ppm, n = 3)
  ) %>%
  # Calculate statistics on the selected subset
  group_by(gas, sample, dayofanalysis) %>%
  summarise(
    avg_ppm_best3 = mean(ppm_selected),
    sd_ppm_best3 = sd(ppm_selected),
    cv_best3 = (sd_ppm_best3 / avg_ppm_best3) * 100,
    n_best3 = sum(!is.na(ppm_selected)),
    .groups = "drop"
  )

message("[Script 3]   - ", nrow(best3_summary),
        " samples eligible for CV-based filtering (n >= 3)")

# ============================================================================
# SECTION 7: COMBINE AND DECIDE WHICH TO USE
# ============================================================================
# For each sample, determine whether using best 3 injections improves CV

message("[Script 3] Comparing CV between all and best 3 injections")

final_summary <- all_injections_summary %>%
  left_join(best3_summary, by = c("gas", "sample", "dayofanalysis")) %>%
  # Flag whether discarding improved CV
  mutate(
    improved_cv = if_else(
      is.na(cv_best3),
      FALSE,                         # Can't compare if no best3 available
      cv_best3 < cv                  # TRUE if best3 CV is lower
    ),
    # Choose between all and best3 based on CV improvement
    avg_ppm = if_else(improved_cv, avg_ppm_best3, avg_ppm),
    sd_ppm = if_else(improved_cv, sd_ppm_best3, sd_ppm),
    n_used = if_else(improved_cv, n_best3, n_all),
    n_discarded = if_else(improved_cv, n_all - n_best3, 0)
  ) %>%
  # Select final output columns
  select(
    gas, sample, dayofanalysis,
    avg_ppm, sd_ppm, n_used, n_discarded
  ) %>%
  # Sort by date and sample name for readability
  arrange(dayofanalysis, sample)

# Log summary of CV-based filtering
n_filtered <- sum(final_summary$n_discarded > 0, na.rm = TRUE)

if (n_filtered > 0) {
  message("[Script 3] CV-based filtering applied to ", n_filtered, 
          " samples")
  message("[Script 3] (improved CV by using best 3 injections)")
}

# ============================================================================
# SECTION 8: CREATE ALL-INJECTIONS SUMMARY
# ============================================================================
# This is the raw summary before any filtering - shows what you actually measured

message("\n[Script 3] ========== Creating Output Files ==========")

summary_all <- all_injections_summary %>%
  mutate(
    n_used = n_all,
    n_discarded = 0
  ) %>%
  select(gas, sample, dayofanalysis, avg_ppm, sd_ppm, n_used, n_discarded) %>%
  # Pivot wider to separate CO2 columns (allows for future multi-gas support)
  pivot_wider(
    id_cols = c(sample, dayofanalysis),
    names_from = gas,
    names_sep = "_",
    values_from = c(avg_ppm, sd_ppm, n_used, n_discarded),
    names_sort = TRUE
  ) %>%
  # Sort for readability
  arrange(dayofanalysis, sample) %>%
  # Select columns in consistent order
  select(
    dayofanalysis, sample,
    everything()
  )

# Save all-injections summary
output_file_all <- paste0(folder_results, "All_Summary_co2_allinjections.csv")
write.csv(summary_all, output_file_all, row.names = FALSE)
message("[Script 3] Saved: All_Summary_co2_allinjections.csv")

# ============================================================================
# SECTION 9: CREATE BEST-3-INJECTIONS SUMMARY
# ============================================================================
# This summary uses CV-based filtering when it improves precision

summary_best3 <- final_summary %>%
  # Pivot wider (same format as summary_all)
  pivot_wider(
    id_cols = c(sample, dayofanalysis),
    names_from = gas,
    names_sep = "_",
    values_from = c(avg_ppm, sd_ppm, n_used, n_discarded),
    names_sort = TRUE
  ) %>%
  # Sort for readability
  arrange(dayofanalysis, sample) %>%
  # Select columns in consistent order
  select(
    dayofanalysis, sample,
    everything()
  )

# Save best-3 summary
output_file_best3 <- paste0(folder_results, "All_Summary_co2_best3inj.csv")
write.csv(summary_best3, output_file_best3, row.names = FALSE)
message("[Script 3] Saved: All_Summary_co2_best3inj.csv")

# ============================================================================
# SECTION 10: CREATE INJECTION-LEVEL DATA FILE
# ============================================================================
# Raw data - all individual injection ppm values for quality control

all_injections_raw <- co2 %>%
  select(gas, dayofanalysis, sample, ml_injected, peak_id, ppm) %>%
  arrange(dayofanalysis, sample, peak_id)

output_file_injections <- paste0(folder_results, "All_Injections_ppm_co2.csv")
write.csv(all_injections_raw, output_file_injections, row.names = FALSE)
message("[Script 3] Saved: All_Injections_ppm_co2.csv")

# ============================================================================
# SECTION 11: PRINT SUMMARY AND STATISTICS
# ============================================================================

message("\n[Script 3] ========== SUMMARY STATISTICS ==========")
message("[Script 3] Processing complete!")

message("\nOutput files created:")
message("  1. All_Summary_co2_allinjections.csv - All injections used")
message("  2. All_Summary_co2_best3inj.csv - CV-optimized (best 3 used when beneficial)")
message("  3. All_Injections_ppm_co2.csv - Individual injection data")

# Print sample of results
message("\nFirst 10 rows of CV-optimized summary:")
print(head(summary_best3, 10))

# Calculate and display filtering statistics
filtering_stats <- final_summary %>%
  summarise(
    total_samples = n(),
    samples_filtered = sum(n_discarded > 0, na.rm = TRUE),
    total_injections = sum(n_used + n_discarded, na.rm = TRUE),
    injections_discarded = sum(n_discarded, na.rm = TRUE),
    avg_ppm_range = paste0(
      round(min(avg_ppm, na.rm = TRUE), 2), " to ",
      round(max(avg_ppm, na.rm = TRUE), 2)
    )
  )

message("\nStatistical Summary:")
message("  - Total unique sample-day combinations: ", 
        filtering_stats$total_samples)
message("  - Samples improved by CV filtering: ", 
        filtering_stats$samples_filtered)
message("  - Total injections processed: ", 
        filtering_stats$total_injections)
message("  - Injections discarded by filtering: ", 
        filtering_stats$injections_discarded)
message("  - ppm range: ", filtering_stats$avg_ppm_range)

message("\n[Script 3] ========== COMPLETE ==========")
message("[Script 3] All results saved to: ", folder_results)

# ============================================================================
# END OF SCRIPT 3
# ============================================================================
